// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyztcCTsdmgh--G5uuNew_pKc19Wup3S8',
    appId: '1:874122880359:web:9ec8ba66fee0401836fbc2',
    messagingSenderId: '874122880359',
    projectId: 'hotel-booking-ec211',
    authDomain: 'hotel-booking-ec211.firebaseapp.com',
    storageBucket: 'hotel-booking-ec211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACzQ2FdXf3YmutfYOz4oq5EqOje5tLKzI',
    appId: '1:874122880359:android:3d789cb789b133dc36fbc2',
    messagingSenderId: '874122880359',
    projectId: 'hotel-booking-ec211',
    storageBucket: 'hotel-booking-ec211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNl4QmAsMYhA4u0K374_vWU_ZurEwkjJ8',
    appId: '1:874122880359:ios:5d03bbf2caf6643536fbc2',
    messagingSenderId: '874122880359',
    projectId: 'hotel-booking-ec211',
    storageBucket: 'hotel-booking-ec211.appspot.com',
    iosBundleId: 'com.example.hotelBooking',
  );
}
